default:
  image: nixos/nix:2.3.4

stages:
  - precompute
  - build
  - test
  - deploy


data:
  stage: precompute
  script:
    - nix-env -if shell.nix -A buildInputs
    - ./update.py
  cache:
    paths:
      - cache*.p
  artifacts:
    paths:
      - data.js

site:
  stage: build
  image: nixery.dev/shell/minify/openssl/gawk
  script:
    - ./build-site.sh
  dependencies:
    - data
  artifacts:
    paths:
      - public

linkchecker:
  stage: test
  script:
    - nix-env -iA nixpkgs.linkchecker
    - linkchecker --verbose public/index.html
  dependencies:
    - site

pages:
  stage: deploy
  script:
    - echo deploying
  dependencies:
    - site
  artifacts:
    paths:
      - public
  only:
    - master
